-- MySQL Script generated by MySQL Workbench
-- Sun Jan  1 14:32:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_shop` DEFAULT CHARACTER SET utf8 ;
USE `e_shop` ;

-- -----------------------------------------------------
-- Table `e_shop`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`category` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`category` (
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`user` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password` VARCHAR(72) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`consumer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`consumer` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`consumer` (
  `user_id` BIGINT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_Consumer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e_shop`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`product` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `cost` DOUBLE NOT NULL,
  `product_type` VARCHAR(50) NOT NULL,
  `category_title` VARCHAR(100) NOT NULL,
  `consumer_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Product_Category`
    FOREIGN KEY (`category_title`)
    REFERENCES `e_shop`.`category` (`title`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`category_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`category_fields` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`category_fields` (
  `category_title` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `field_type` VARCHAR(100) NOT NULL,
  `regex` VARCHAR(400) NOT NULL,
  `flag_fixed_multiple_values` TINYINT NOT NULL,
  PRIMARY KEY (`category_title`, `name`),
  CONSTRAINT `fk_category_fields_category1`
    FOREIGN KEY (`category_title`)
    REFERENCES `e_shop`.`category` (`title`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`product_pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`product_pictures` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`product_pictures` (
  `product_id` BIGINT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`product_id`, `name`),
  CONSTRAINT `fk_product_pictures_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e_shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `e_shop`.`product_field_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`product_field_values` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`product_field_values` (
  `category_field_title` VARCHAR(100) NOT NULL,
  `category_field_name` VARCHAR(100) NOT NULL,
  `product_id` BIGINT NOT NULL,
  `field_value` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`category_field_title`, `category_field_name`, `product_id`),
  CONSTRAINT `fk_product_field_values_category_fields1`
    FOREIGN KEY (`category_field_title` , `category_field_name`)
    REFERENCES `e_shop`.`category_fields` (`category_title` , `name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_field_values_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e_shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`admin` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`admin` (
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e_shop`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`support_specialist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`support_specialist` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`support_specialist` (
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_support_specialist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e_shop`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`comment` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`comment` (
  `product_id` BIGINT NOT NULL,
  `consumer_id` BIGINT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `value` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`product_id`, `consumer_id`, `datetime`),
  CONSTRAINT `fk_comment_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e_shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`log` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(400) NOT NULL,
  `level` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `consumer_id` BIGINT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_log_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`product_bought`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`product_bought` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`product_bought` (
  `product_id` BIGINT NOT NULL,
  `consumer_id` BIGINT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `payment_type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_bought_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `e_shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_bought_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`support_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`support_message` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`support_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `flag_read` TINYINT NOT NULL,
  `return_message` VARCHAR(1000),
  `consumer_id` BIGINT NOT NULL,
  `support_specialist_id` BIGINT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_support_message_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_support_message_support_specialist1`
    FOREIGN KEY (`support_specialist_id`)
    REFERENCES `e_shop`.`support_specialist` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_shop`.`confirmation_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_shop`.`confirmation_token` ;

CREATE TABLE IF NOT EXISTS `e_shop`.`confirmation_token` (
  `consumer_id` BIGINT NOT NULL,
  `confirmed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `token` INT NOT NULL,
  PRIMARY KEY (`consumer_id`),
  CONSTRAINT `fk_confirmation_token_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `e_shop`.`consumer` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

### password = aleksandar, username = aleksandar
insert into user(first_name, last_name, username, password) values("Aleksandar", "Aleksandrovic", "aleksandar", "$2a$10$owz9eb/YcewvPeffNbr/5OZ6OQ0SzrhUiri8m3R9uWQe.rKVwaGse");
insert into admin values(1);

### password = jovana, username = jovana
insert into user(first_name, last_name, username, password) values("Jovana", "Jovanovic", "jovana", "$2a$10$0jQ/td8uG6TXCCrfjltu9uHyooRDpqZZ/NzB0/8GvWpViOx8e0wYq");
insert into support_specialist values(2);

### password = jelena, username = jelena
insert into user(first_name, last_name, username, password) values("Jelena", "Jelenovic", "jelena", "$2y$10$cn2XXno5z3booEX75kERB.ZDu7JGS.D.1lIb9vGz2nw/d7n71tXx6");
insert into consumer values(3, "jelena@gmail.com", "065902176", "Prijedor", null);

### password = darko123, username = darko
insert into user(first_name, last_name, username, password) values("Darko", "Darkovic", "darko", "$2y$10$RWM3UusjTLagU.yb4H3pR.WKkU84sjkijPBDpiFtPg9lvbUGxlBGu");
insert into consumer values(4, "darko@outlook.de", "065100200", "Budimpesta", null);